version: '2'

services:
  marketplace-app:
    image: 'docker-marketplace:latest'
    build:
      context: .
    container_name: marketplace-app
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/marketplace?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=DEV
    links:
      - db

  db:
    image: 'mysql:8.0.23'
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=marketplace
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root